<?php

namespace App\Clients;

class ClientConstants
{

    const TEMP_API_BASE_PARAMS = [
        "DatetimeRegStart" => "",
        "DatetimeRegEnd" => "",
        "CustName" => "",
        "Phone" => "",
        "Sex" => "",
        "MediaSourceType" => "",
        "MediaSource" => "",
        "CreatedBy" => "",
        "TmpCustRegType" => "",
        "TmpCustRegTypeMenus" => "",
        "LastRecallDateStart" => "",
        "LastRecallDateEnd" => "",
        "HaveAfterCall" => "",
        "PlanRecallEmp" => "",
        "SalesConsultantId" => "",
        "IsPhone" => "",
        "RecallCountMin" => "",
        "RecallCountMax" => "",
        "DatetimeArriveStart" => "",
        "DatetimeArriveEnd" => "",
        "Remark" => "",
        "Province" => "",
        "City" => "",
        "Area" => "",
        "IsOrdered" => "",
        "Job" => "",
        "AttentionRemark" => "",
        "Address" => "",
        "QQ" => "",
        "WeiXinNo" => "",
        "StartAge" => "",
        "EndAge" => "",
        "LabelTypeId" => "",
        "CustLabelId" => "",
        "NoCustLabelId" => "",
        "NoCustLabelMenus" => "",
        "RecommendEmpId" => "",
        "RecommendCustName" => "",
        "RecommendCustPhone" => "",
        "RecommendCustCardno" => "",
        "TempCustComingNo" => "",
        "IncomeCapacity" => "",
        "GuestId" => "",
        "LastRecallExecuteBy" => "",
        "LastRecallFeedback" => "",
        "isSearch" => "1",
        "pageSize" => "100",
        "pageCurrent" => "1",
        "iscompay" => "0",
        "EmployeeToChannel" => "",
        "orderField" => "",
        "orderDirection" => "",
        "total" => "",
    ];

}
