<?php

namespace App\Admin\Controllers;

use App\Models\AccountData;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;

class AccountDataController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'App\Models\AccountData';

    public function create(Content $content)
    {
        return $content
            ->title($this->title())
            ->description($this->description['create'] ?? trans('admin.create'))
            ->row(function (Grid\Row $row) {
                $row->column(12, function (Grid\Column $column) {
                    $column->view();

                });
            });

        return parent::create($content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        $grid = new Grid(new AccountData);

        $grid->column('id', __('Id'));
        $grid->column('name', __('Name'));
        $grid->column('rebate', __('Rebate'));
        $grid->column('keyword', __('Keyword'));
        $grid->column('crm_keyword', __('Crm keyword'));
        $grid->column('channel_id', __('Channel id'));
        $grid->column('created_at', __('Created at'));
        $grid->column('updated_at', __('Updated at'));

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(AccountData::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('name', __('Name'));
        $show->field('rebate', __('Rebate'));
        $show->field('keyword', __('Keyword'));
        $show->field('crm_keyword', __('Crm keyword'));
        $show->field('channel_id', __('Channel id'));
        $show->field('created_at', __('Created at'));
        $show->field('updated_at', __('Updated at'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new AccountData);

        $form->text('name', __('Name'));
        $form->text('rebate', __('Rebate'));
        $form->text('keyword', __('Keyword'));
        $form->text('crm_keyword', __('Crm keyword'));
        $form->number('channel_id', __('Channel id'));

        return $form;
    }
}
