<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TempCustomerData extends Model
{
    public static $excelFields = [
        "is_order",
        "is_arriving",
        "temp_visitor",
        "phone",
        "gender",
        "archive_type",
        "online_customer",
        "return_visit_count",
        "archive_by",
        "return_visit_by",
        "referrer",
        "archive_date",
        "arriving_date",
        "last_return_visit_date",
        "medium_type",
        "medium_source",
        "beauty_salon_type",
        "beauty_salon_name",
        "tag_name",
        "comment",
        "focus_question",
        "marriage",
        "age",
        "financial_ability",
        "province",
        "county",
        "area",
        "address",
        "career",
        "weixin",
        "qq",
        "reservation_number",
        "visitor_id",
        "staff_referrer",
    ];

    protected $fillable = [
        "is_order",
        "is_arriving",
        "temp_visitor",
        "phone",
        "gender",
        "archive_type",
        "online_customer",
        "return_visit_count",
        "archive_by",
        "return_visit_by",
        "referrer",
        "archive_date",
        "arriving_date",
        "last_return_visit_date",
        "medium_type",
        "medium_source",
        "beauty_salon_type",
        "beauty_salon_name",
        "tag_name",
        "comment",
        "focus_question",
        "marriage",
        "age",
        "financial_ability",
        "province",
        "county",
        "area",
        "address",
        "career",
        "weixin",
        "qq",
        "reservation_number",
        "visitor_id",
        "staff_referrer",

        'archive_id',
        'customer_id',
        'medium_id',
        'type',
    ];
}
